name: Update Unicode 16.0.0

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  RUSTFLAGS: -Dwarnings

jobs:
  unicode-16:
    name: Update to Unicode 16.0.0
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: ucd-generate
      - run: curl -LO https://www.unicode.org/Public/zipped/16.0.0/UCD.zip
      - run: unzip UCD.zip -d UCD
      - run: ucd-generate property-bool UCD --include ID_Start,ID_Continue > tests/tables/tables.rs
      - run: ucd-generate property-bool UCD --include ID_Start,ID_Continue --fst-dir tests/fst
      - run: ucd-generate property-bool UCD --include ID_Start,ID_Continue --trie-set > tests/trie/trie.rs
      - run: cargo run --manifest-path generate/Cargo.toml
      - run: rm -rf UCD UCD.zip
      - run: git diff --stat