name: Update Unicode

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Unicode Version

permissions: {}

jobs:
  unicode:
    name: Update Unicode
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: oxc-project/setup-rust@v1.0.0
      - uses: taiki-e/install-action@v2
        with:
          tool: ucd-generate
      - run: curl -LO https://www.unicode.org/Public/zipped/latest/UCD.zip
      - run: unzip UCD.zip -d UCD
      - run: ucd-generate property-bool UCD --include ID_Start,ID_Continue > tests/tables/tables.rs
      - run: ucd-generate property-bool UCD --include ID_Start,ID_Continue --fst-dir tests/fst
      - run: ucd-generate property-bool UCD --include ID_Start,ID_Continue --trie-set > tests/trie/trie.rs
      - run: cargo run --manifest-path generate/Cargo.toml
      - run: rm -rf UCD UCD.zip
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: Update Unicode
          base: main
          title: Update Unicode
          assignees: Boshen
